modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="eunomia"
version="${version}"
displayName="Eunomia"
description="Lib for common stuff (//TODO adjust this)"
authors="zannagh"
logoFile="assets/eunomia/icon.png"

[[mixins]]
config="eunomia.mixins.json"

[[mixins]]
config="eunomia.client.mixins.json"

[[dependencies."eunomia"]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies."eunomia"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version}"
ordering="NONE"
side="BOTH"
