plugins {
    java
    `java-library`
    jacoco
    id("eunomia-publish")
}

// The networking core is deliberately Minecraft-free: plain Java + Gson only. That is what lets
// the Bukkit-family plugin (:paper) depend on it without dragging NMS / loader classes onto its
// classpath, while the loaders (:common) layer their StreamCodec / CustomPacketPayload adapter on
// top. A single artifact covers every game version.
group = "de.zannagh.eunomia"
val semVer = resolveSemVer()
version = semVer

base {
    archivesName.set("eunomia-core")
}

// The mod's own version has to be readable at RUNTIME (it derives the upstream API path segment,
// see de.zannagh.eunomia.common.ApiVersion), and :core is Minecraft-free - no FabricLoader, no
// Bukkit PluginDescriptionFile. A generated CLASS rather than a resource on purpose: :core is
// shaded into the Paper plugin jar, where a resource name could collide with a host's.
val generateBuildInfo = tasks.register("generateBuildInfo") {
    val version = semVer
    val outputDir = layout.buildDirectory.dir("generated/sources/buildInfo/java/main")
    inputs.property("version", version)
    outputs.dir(outputDir)
    doLast {
        val target = outputDir.get().asFile.resolve("de/zannagh/eunomia/common/BuildInfo.java")
        target.parentFile.mkdirs()
        target.writeText(
            """
            package de.zannagh.eunomia.common;

            /** Build-time constants injected by Gradle. Do not edit - regenerated by the `generateBuildInfo` task. */
            public final class BuildInfo {

                /** The mod version this artifact was built at, e.g. {@code 0.3.0} or {@code 0.3.1-preview.5}. */
                public static final String VERSION = "${version}";

                private BuildInfo() {
                }
            }
            """.trimIndent() + "\n"
        )
    }
}

sourceSets.main {
    java.srcDir(generateBuildInfo)
}


repositories {
    mavenCentral()
}

dependencies {
    // Gson and SLF4J are compileOnly on purpose: every consumer already ships them (Minecraft on the
    // loaders, paper-api on the Paper plugin), and MC pins gson to a strict version - so forcing a
    // version here would clash on the NeoForge classpath. Not declaring a version keeps :core a good
    // citizen on whatever classpath it lands on. Core's own tests pull their own copies below.
    compileOnly("com.google.code.gson:gson:2.11.0")
    compileOnly("org.slf4j:slf4j-api:2.0.16")
    compileOnly("org.jspecify:jspecify:1.0.0")

    testImplementation(platform("org.junit:junit-bom:6.0.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("com.google.code.gson:gson:2.11.0")
    testImplementation("org.slf4j:slf4j-api:2.0.16")
    testImplementation("org.jspecify:jspecify:1.0.0")
}

java {
    // Java 17: the lowest baseline across the whole matrix (a 1.20.1 server still runs on 17), so
    // the one core artifact loads everywhere the loaders and Paper do.
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    }
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}

// The MC-free networking core is the primary maven artifact a consuming mod (armor-hider) pulls in
// - either on its build classpath or jar-in-jar'd. Publishes the library jar + sources under
// `de.zannagh.eunomia:eunomia-core`.
publishing {
    publications {
        create<MavenPublication>("maven") {
            artifactId = "eunomia-core"
            from(components["java"])
        }
    }
}
