<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eunomia.Server.Core\Eunomia.Server.Core.csproj" />
    <ProjectReference Include="..\Eunomia.Server.Api\Eunomia.Server.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fixtures\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
